#include <stdio.h>
#include <stdint.h>
#include <stddef.h>
#include <assimp/scene.h>
#include <assimp/mesh.h>
#include <assimp/anim.h>
#include <assimp/material.h>
#include <assimp/camera.h>
#include <assimp/light.h>
#include <assimp/postprocess.h>

typedef struct {
  const char *c_name;
  const char *odin_name;
  size_t size;
} Struct_Info;

#define X(type) { "ai" #type, #type, sizeof(struct ai##type) }

int main(void) {
  Struct_Info structs[] = {
    X(VectorKey),
    X(QuatKey),
    X(NodeAnim),
    X(Animation),
    X(String),
    X(MemoryInfo),
    X(Camera),
    X(Material),
    X(Light),
    X(Face),
    X(VertexWeight),
    X(Bone),
    X(AnimMesh),
    X(Mesh),
    X(Vector2D),
    X(Vector3D),
    X(Quaternion),
    X(Matrix3x3),
    X(Matrix4x4),
    X(Plane),
    X(Ray),
    X(Color3D),
    X(Color4D),
    X(Texel),
    X(Texture),
    X(Node),
    X(Scene),
  };

  FILE *f = fopen("static_asserts.odin", "w");
  if (!f) {
    perror("fopen");
    return 1;
  }

  fprintf(f, "// This file was generated by " __FILE__ "\n");
  fprintf(f, "\n");

  fprintf(f, "package assimp\n");
  fprintf(f, "\n");

  for (size_t i = 0; i < sizeof(structs) / sizeof(structs[0]); ++i) {
    Struct_Info s = structs[i];
    fprintf(f, "#assert(size_of(%s) == %zu)\n", s.odin_name, s.size, s.c_name);
  }

  fclose(f);
  printf("Generated static_asserts.odin successfully.\n");

  return 0;
}
